/**
 * Canonical Permission List - Enterprise-Grade RBAC
 * This is the single source of truth for all permissions in the system.
 */
export const PERMISSIONS = {
  // 🧑 Profile & Account
  PROFILE_READ_SELF: "PROFILE:READ:SELF",
  PROFILE_UPDATE_SELF_LIMITED: "PROFILE:UPDATE:SELF_LIMITED",
  PROFILE_UPDATE_SELF_FULL: "PROFILE:UPDATE:SELF_FULL",
  PROFILE_UPDATE_STUDENT_UNDER_BATCH: "PROFILE:UPDATE:STUDENT_UNDER_BATCH",
  PROFILE_UPDATE_STUDENT_ANY: "PROFILE:UPDATE:STUDENT_ANY",
  PASSWORD_CHANGE_SELF: "PASSWORD:CHANGE:SELF",

  // 🧑‍🎓 Student Data & Access
  STUDENT_READ_SELF: "STUDENT:READ:SELF",
  STUDENT_READ_UNDER_BATCH: "STUDENT:READ:UNDER_BATCH",
  STUDENT_READ_ANY: "STUDENT:READ:ANY",
  STUDENT_CREATE: "STUDENT:CREATE",
  STUDENT_UPDATE_STATUS_UNDER_BATCH: "STUDENT:UPDATE_STATUS:UNDER_BATCH",
  STUDENT_UPDATE_STATUS_ANY: "STUDENT:UPDATE_STATUS:ANY",

  // 🧑‍🏫 Teacher Management
  TEACHER_READ_SELF: "TEACHER:READ:SELF",
  TEACHER_READ_ANY: "TEACHER:READ:ANY",
  TEACHER_CREATE: "TEACHER:CREATE",
  TEACHER_UPDATE: "TEACHER:UPDATE",

  // 📚 Batches & Scheduling
  BATCH_READ_OWN: "BATCH:READ:OWN",
  BATCH_READ_UNDER_TEACHER: "BATCH:READ:UNDER_TEACHER",
  BATCH_READ_ANY: "BATCH:READ:ANY",
  BATCH_CREATE: "BATCH:CREATE",
  BATCH_UPDATE: "BATCH:UPDATE",
  BATCH_DELETE: "BATCH:DELETE",

  // 🗓 Attendance
  ATTENDANCE_READ_SELF: "ATTENDANCE:READ:SELF",
  ATTENDANCE_READ_UNDER_BATCH: "ATTENDANCE:READ:UNDER_BATCH",
  ATTENDANCE_READ_ANY: "ATTENDANCE:READ:ANY",
  ATTENDANCE_UPDATE_UNDER_BATCH: "ATTENDANCE:UPDATE:UNDER_BATCH",
  ATTENDANCE_UPDATE_ANY: "ATTENDANCE:UPDATE:ANY",

  // 🔁 Batch Change Requests
  BATCH_CHANGE_CREATE: "BATCH_CHANGE:CREATE",
  BATCH_CHANGE_READ_UNDER_BATCH: "BATCH_CHANGE:READ:UNDER_BATCH",
  BATCH_CHANGE_READ_ANY: "BATCH_CHANGE:READ:ANY",
  BATCH_CHANGE_APPROVE_UNDER_BATCH: "BATCH_CHANGE:APPROVE:UNDER_BATCH",
  BATCH_CHANGE_APPROVE_ANY: "BATCH_CHANGE:APPROVE:ANY",

  // 📢 Announcements
  ANNOUNCEMENT_READ: "ANNOUNCEMENT:READ",
  ANNOUNCEMENT_CREATE: "ANNOUNCEMENT:CREATE",
  ANNOUNCEMENT_UPDATE: "ANNOUNCEMENT:UPDATE",
  ANNOUNCEMENT_DELETE: "ANNOUNCEMENT:DELETE",

  // 🧠 Practice Library
  PRACTICE_ACCESS: "PRACTICE:ACCESS",

  // 🎥 Zoom / Live Classes
  ZOOM_POST_UNDER_BATCH: "ZOOM:POST:UNDER_BATCH",
  ZOOM_POST_ANY: "ZOOM:POST:ANY",
  ZOOM_VIEW_UNDER_BATCH: "ZOOM:VIEW:UNDER_BATCH",
  ZOOM_VIEW_ALL: "ZOOM:VIEW:ALL",

  // 📊 Analytics & Reports
  ANALYTICS_VIEW_UNDER_BATCH: "ANALYTICS:VIEW:UNDER_BATCH",
  ANALYTICS_VIEW_ANY: "ANALYTICS:VIEW:ANY",
  REPORT_GENERATE: "REPORT:GENERATE",

  // 💳 Payments
  PAYMENT_READ_SELF: "PAYMENT:READ:SELF",
  PAYMENT_READ_UNDER_BATCH: "PAYMENT:READ:UNDER_BATCH",
  PAYMENT_READ_ANY: "PAYMENT:READ:ANY",

  // 📅 Holidays & Scheduling
  HOLIDAY_READ: "HOLIDAY:READ",
  HOLIDAY_DECLARE_UNDER_BATCH: "HOLIDAY:DECLARE:UNDER_BATCH",
  HOLIDAY_DECLARE_ANY: "HOLIDAY:DECLARE:ANY",
  SCHEDULE_RESCHEDULE_UNDER_BATCH: "SCHEDULE:RESCHEDULE:UNDER_BATCH",
  SCHEDULE_RESCHEDULE_ANY: "SCHEDULE:RESCHEDULE:ANY",

  // ⚙️ System / Admin
  ROLE_ASSIGN: "ROLE:ASSIGN",
  DATABASE_ACCESS: "DATABASE:ACCESS",
  SYSTEM_CONFIGURE: "SYSTEM:CONFIGURE",
} as const;

// Type helper for TypeScript autocompletion
export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

// All permission values as an array
export const ALL_PERMISSIONS = Object.values(PERMISSIONS);
