import { PERMISSIONS } from "./permissions";

/**
 * Role to Permissions Mapping - Authoritative Table
 * This defines which permissions each role has access to.
 */

// 🟡 GUEST - Limited read-only access
export const GUEST_PERMISSIONS = [
  PERMISSIONS.PROFILE_READ_SELF,
  PERMISSIONS.STUDENT_READ_SELF,
  PERMISSIONS.PRACTICE_ACCESS,
  PERMISSIONS.ANNOUNCEMENT_READ,
  PERMISSIONS.HOLIDAY_READ, // Can view holiday calendar
];

// 🟢 STUDENT - Basic user permissions
export const STUDENT_PERMISSIONS = [
  PERMISSIONS.PROFILE_READ_SELF,
  PERMISSIONS.PROFILE_UPDATE_SELF_LIMITED,
  PERMISSIONS.PASSWORD_CHANGE_SELF,
  
  PERMISSIONS.STUDENT_READ_SELF,
  
  PERMISSIONS.BATCH_READ_OWN,
  PERMISSIONS.ATTENDANCE_READ_SELF,
  
  PERMISSIONS.BATCH_CHANGE_CREATE,
  
  PERMISSIONS.PRACTICE_ACCESS,
  PERMISSIONS.ANNOUNCEMENT_READ,
  PERMISSIONS.ZOOM_VIEW_UNDER_BATCH,

  // Payments
  PERMISSIONS.PAYMENT_READ_SELF,

  // Holidays
  PERMISSIONS.HOLIDAY_READ,
];

// 🔵 TEACHER - Includes all student permissions + teacher-specific
export const TEACHER_PERMISSIONS = [
  ...STUDENT_PERMISSIONS,
  
  PERMISSIONS.TEACHER_READ_SELF,
  
  PERMISSIONS.STUDENT_READ_UNDER_BATCH,
  PERMISSIONS.PROFILE_UPDATE_STUDENT_UNDER_BATCH,
  
  PERMISSIONS.BATCH_READ_UNDER_TEACHER,
  
  PERMISSIONS.ATTENDANCE_READ_UNDER_BATCH,
  PERMISSIONS.ATTENDANCE_UPDATE_UNDER_BATCH,
  
  PERMISSIONS.BATCH_CHANGE_READ_UNDER_BATCH,
  PERMISSIONS.BATCH_CHANGE_APPROVE_UNDER_BATCH,
  
  PERMISSIONS.ANNOUNCEMENT_CREATE,
  PERMISSIONS.ANNOUNCEMENT_UPDATE,
  
  PERMISSIONS.ZOOM_POST_UNDER_BATCH,
  
  PERMISSIONS.ANALYTICS_VIEW_UNDER_BATCH,

  // Payments (can see students in their batches)
  PERMISSIONS.PAYMENT_READ_UNDER_BATCH,

  // Holidays & Scheduling (can manage for their batches)
  PERMISSIONS.HOLIDAY_DECLARE_UNDER_BATCH,
  PERMISSIONS.SCHEDULE_RESCHEDULE_UNDER_BATCH,
];

// 🔴 ADMIN - Full system access
export const ADMIN_PERMISSIONS = [
  ...TEACHER_PERMISSIONS,
  
  PERMISSIONS.PROFILE_UPDATE_SELF_FULL,
  PERMISSIONS.PROFILE_UPDATE_STUDENT_ANY,
  
  PERMISSIONS.STUDENT_READ_ANY,
  PERMISSIONS.STUDENT_CREATE,
  PERMISSIONS.STUDENT_UPDATE_STATUS_ANY,
  
  PERMISSIONS.TEACHER_READ_ANY,
  PERMISSIONS.TEACHER_CREATE,
  PERMISSIONS.TEACHER_UPDATE,
  
  PERMISSIONS.BATCH_READ_ANY,
  PERMISSIONS.BATCH_CREATE,
  PERMISSIONS.BATCH_UPDATE,
  PERMISSIONS.BATCH_DELETE,
  
  PERMISSIONS.ATTENDANCE_READ_ANY,
  PERMISSIONS.ATTENDANCE_UPDATE_ANY,
  
  PERMISSIONS.BATCH_CHANGE_READ_ANY,
  PERMISSIONS.BATCH_CHANGE_APPROVE_ANY,
  
  PERMISSIONS.ANNOUNCEMENT_DELETE,
  
  PERMISSIONS.ZOOM_POST_ANY,
  PERMISSIONS.ZOOM_VIEW_ALL,
  
  PERMISSIONS.ANALYTICS_VIEW_ANY,
  PERMISSIONS.REPORT_GENERATE,

  // Payments (full access)
  PERMISSIONS.PAYMENT_READ_ANY,

  // Holidays & Scheduling (full access)
  PERMISSIONS.HOLIDAY_DECLARE_ANY,
  PERMISSIONS.SCHEDULE_RESCHEDULE_ANY,
  
  PERMISSIONS.ROLE_ASSIGN,
  PERMISSIONS.DATABASE_ACCESS,
  PERMISSIONS.SYSTEM_CONFIGURE,
];

/**
 * Role Permission Map - Easy lookup
 */
export const ROLE_PERMISSIONS_MAP = {
  GUEST: GUEST_PERMISSIONS,
  STUDENT: STUDENT_PERMISSIONS,
  TEACHER: TEACHER_PERMISSIONS,
  ADMIN: ADMIN_PERMISSIONS,
} as const;

/**
 * Get permissions for a role
 */
export function getSeedPermissionsForRole(roleName: string): string[] {
  const normalized = roleName.toUpperCase() as keyof typeof ROLE_PERMISSIONS_MAP;
  return ROLE_PERMISSIONS_MAP[normalized] || [];
}


/**
 * Check if a role has a specific permission
 */
export function roleHasPermission(roleName: string, permission: string): boolean {
  const permissions = getSeedPermissionsForRole(roleName);
  return permissions.includes(permission);
}
